force-app/main/default/objects/Account/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <description>Id used in the external service.</description>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/External_URL__c.field-meta.xml
<CustomField>
    <fullName>External_URL__c</fullName>
    <formula>IF( AND(
       ISBLANK(Website),
       ISBLANK(Parent_Account__r.Website)
    ),
    &quot;&quot;,
    IF( NOT(ISBLANK(Parent_Account__r.Website)),
        Parent_Account__r.Website + &quot;/&quot; + External_ID__c,
        Website + &quot;/&quot; + External_ID__c
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>External URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Child_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHandler.cls
public with sharing class AccountTriggerHandler {
    public void beforeInsert(List<Account> newRecords) {
        for (Account newRecord : newRecords) {
            // TBD
        }
    }

    public void beforeUpdate(
        List<Account> oldRecords,
        Map<ID, Account> oldRecordsMap,
        List<Account> newRecords,
        Map<ID, Account> newRecordsMap
    ) {
        for (Account newRecord : newRecords) {
            // TBD
        }
    }

    public class DataLayer implements IDataLayer {
        public Map<ID, Account> getParentAndChildAccountsMap(Set<ID> parentIds) {
            return new Map<ID, Account>(
                [ SELECT Id, Name, External_URL__c, Website, External_ID__c,
                    // Retrives the same fields from the child records
                    (   SELECT Id, Name, External_URL__c, Website, External_ID__c 
                        FROM Child_Accounts__r 
                    )
                    FROM Account
                    WHERE Id IN :parentIds
                ]
            );
        }
    }

    public interface IDataLayer {
        Map<ID, Account> getParentAndChildAccountsMap(Set<ID> parentIds);
    }
}